// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	hospital "health-app/internal/domain/hospital"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetByHCode provides a mock function with given fields: ctx, hcode
func (_m *Repository) GetByHCode(ctx context.Context, hcode string) (*hospital.Hospital, error) {
	ret := _m.Called(ctx, hcode)

	if len(ret) == 0 {
		panic("no return value specified for GetByHCode")
	}

	var r0 *hospital.Hospital
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*hospital.Hospital, error)); ok {
		return rf(ctx, hcode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *hospital.Hospital); ok {
		r0 = rf(ctx, hcode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hospital.Hospital)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hcode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
