// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	patient "his/internal/domain/patient"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id string) (*patient.Patient, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *patient.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*patient.Patient, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *patient.Patient); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*patient.Patient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchPatients provides a mock function with given fields: ctx, filters
func (_m *Repository) SearchPatients(ctx context.Context, filters patient.PatientSearchFilter) ([]*patient.Patient, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for SearchPatients")
	}

	var r0 []*patient.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, patient.PatientSearchFilter) ([]*patient.Patient, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, patient.PatientSearchFilter) []*patient.Patient); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*patient.Patient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, patient.PatientSearchFilter) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
