// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	patient "health-app/internal/domain/patient"

	mock "github.com/stretchr/testify/mock"
)

// Services is an autogenerated mock type for the Services type
type Services struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, hisUrl, id
func (_m *Services) GetByID(ctx context.Context, hisUrl string, id string) (*patient.Patient, error) {
	ret := _m.Called(ctx, hisUrl, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *patient.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*patient.Patient, error)); ok {
		return rf(ctx, hisUrl, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *patient.Patient); ok {
		r0 = rf(ctx, hisUrl, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*patient.Patient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, hisUrl, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchPatients provides a mock function with given fields: ctx, hisUrl, filters
func (_m *Services) SearchPatients(ctx context.Context, hisUrl string, filters patient.PatientsSearchRequest) ([]*patient.Patient, error) {
	ret := _m.Called(ctx, hisUrl, filters)

	if len(ret) == 0 {
		panic("no return value specified for SearchPatients")
	}

	var r0 []*patient.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, patient.PatientsSearchRequest) ([]*patient.Patient, error)); ok {
		return rf(ctx, hisUrl, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, patient.PatientsSearchRequest) []*patient.Patient); ok {
		r0 = rf(ctx, hisUrl, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*patient.Patient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, patient.PatientsSearchRequest) error); ok {
		r1 = rf(ctx, hisUrl, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServices creates a new instance of Services. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *Services {
	mock := &Services{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
